name: CI - Test and Lint

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          token: ${{ secrets.GITHUB_TOKEN }} # ensures auth to private modules

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Linter
        run: golangci-lint run ./...

      - name: Run Tests
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }} # Only required for private repos

  checks:
    name: Check Tests
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Linter on Checks
        run: golangci-lint run ./...

      - name: Run check tests
        run: go test ./...
